info:
  project:
    name: jba-msa-payment-order
    version: 1.0.0

spring:
  application:
    name: jba-msa-payment-order
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: on
    lazy-initialization: on
  web-flux:
    base-path: /
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd'T'HH:mm:ssZ
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      show-sql: true

  datasource:
    initialization-mode: always
    initialize: true
    schema: classpath:/schema.sql
    continue-on-error: true

logging:
  level:
    org.springframework: info
    org.springframework.web: DEBUG
    org.springframework.boot: DEBUG
    com.test.payment.order: DEBUG

test:
  payment-order:
    orders:
      path: /payment-orders
