server:
  port: 8081
  error:
      include-message: always
spring:
  #  r2dbc:
  #    url: r2dbc:postgresql://ec2-3-234-204-26.compute-1.amazonaws.com:5432/d1pvtspeuckn4b?sslMode=require
  #    password: ff0f67f75c39512c0aa5e2cc2df5ad90e5d791a8984bc8cbc5b912d65d64a0d4
  #    username: qlrzobvooadkdf
#  r2dbc:
#    url: r2dbc:postgresql://tsdbadmin@hf4k1dp668.ps1ubj9bd0.tsdb.cloud.timescale.com:33285/tsdb?sslmode=require
#    password: f3bwc3ypw8c7azv9
#    username: tsdbadmin
  r2dbc:
    url: r2dbc:postgresql://db:5432/database
    username: username
    password: password

test:
  payment-order:
    orders:
      path: /payment-orders